# Generated by Django 3.1 on 2020-08-31 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model_PollApp_Question',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('poll_question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='model_PollApp_Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_answer', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('index_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PollApp.model_pollapp_question')),
            ],
        ),
    ]
